version: "3"

services:
    jenkins:
        build: ./modules/jenkins
        container_name: api-test-jenkins
        volumes:
            - ./userdata/result:/var/jenkins_home/workspace:consistent
            - ./userdata/jenkins_home:/var/jenkins_home:consistent
            - ./userdata/environment:/environment
        ports:
            - 8080:8080
    python:
        build: ./modules/python
        container_name: api-test-python
        environment:
            DIRECTORY: /api_test
            SUCCESS: 200
            ERROR: 424
            PORT: 80
        volumes:
            - ./userdata/api_test:/api_test:consistent
            - ./userdata/result:/result:consistent
            - ./userdata/environment:/environment
