version: "3"

services: 
    jenkins:
        build: ./modules/jenkins
        container_name: api-test-jenkins
        volumes: 
            - ./userdata/result:/result:consistent
            - ./userdata/jenkins_home:/var/jenkins_home:consistent
            - ./userdata/environment:/environment
        ports:
            - 8080:8080
    python:
        build: ./modules/python
        container_name: api-test-python
        volumes:
            - ./userdata/api_test:/api_test:consistent
            - ./userdata/result:/result:consistent
            - ./userdata/environment:/environment